question_data = [
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Mathematics",
                  "question": "An equilateral triangle always has every angle measuring 60&deg;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
                  "question": "&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In &quot;Super Mario 3D World&quot;, the Double Cherry power-up originated from a developer accidentally making two characters controllable.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Comics",
                  "question": "The &quot;Pepe&quot; meme originated from a comic drawn by Matt Furie called &quot;Boy&#039;s Club&quot;?",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
                  "question": "Dracula is destroyed by contact with sunlight",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "George Lucas directed the entire original Star Wars trilogy.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science: Mathematics",
                  "question": "A scalene triangle has two sides of equal length.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
                  "question": "A group of islands is called an &#039;archipelago&#039;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "question": "When you cry in space, your tears stick to your face.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "History",
                  "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Codemasters is the developer of the Gran Turismo series.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
                  "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In &quot;Super Mario Bros.&quot;, the clouds and bushes have the same artwork and are just different colors.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
                  "question": "An atom contains a nucleus.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
                  "question": "Tony Hawk&#039;s extreme sports videogames revolve around performing professional BMX tricks.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "easy", "category": "Geography",
                  "question": "Alaska is the largest state in the United States.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}
]
